# Generated by Django 4.2.1 on 2023-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=50, null=True)),
                ("last_name", models.CharField(default="", max_length=50, null=True)),
                ("email", models.EmailField(default="", max_length=50, null=True)),
                ("password", models.CharField(default="", max_length=255, null=True)),
                ("mobile", models.BigIntegerField()),
                ("gender", models.CharField(default="", max_length=50, null=True)),
            ],
        ),
    ]
