# Generated by Django 4.2.1 on 2023-06-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify", "0003_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Category",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="product",
            name="pro_image",
            field=models.ImageField(upload_to="uploads/product/"),
        ),
    ]
